ejs:
  environment:
    original:
      baseName: CatinyBackend
      author: yuvytung
      serverPort: 21200
      prefix: sys
      suffix: ""
      entityPrefix: ""
      entitySuffix: ""
      dtoSuffix: DTO
      nativeLanguage: en
      packageFolder: com/regitiny/catiny/backend
      serviceDiscoveryType: true
      websocket: true
      searchEngine: elasticsearch
      messageBroker: kafka
      clientPackageManager: yarn
      buildTool: gradle
      entityType: mongoose
      #      entityType: typeorm
      database: mongodb # mysql, mariadb, postgres
      #      database: mysql # mysql, mariadb, postgres
      devDatabase: mongodb-memory # sqlite , mongodb-memory
      #      devDatabase: sqlite # sqlite , mongodb
      prodDatabase: mongodb
      #      prodDatabase: mysql
      clientTheme: cerulean # cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, morph, pulse, quartz, sandstone, simplex, sketchy, slate, solar, spacelab, superhero, united, vapor, yeti, zephyr,
modules: # Note : that the order will affect the result
  backend-nestjs-new:
    base: base # tất cả đều cần chạy base
    search: elasticsearch
    cache: redis
    database: mongodb
#    database: sql

#  frontend-reactjs:
#    test: cypress
#    protractor: true

file:
  typeExtensions:
    binary:
      # # Audio
      - kar
      - m4a
      - mid
      - midi
      - mp3
      - ogg
      - ra
      # VIDEO
      - 3gpp
      - 3gp
      - as
      - asf
      - asx
      - fla
      - flv
      - m4v
      - mng
      - mov
      - mp4
      - mpeg
      - mpg
      - swc
      - swf
      - webm
      # ARCHIVES
      - 7z
      - gz
      - rar
      - tar
      - zip
      # FONTS
      - ttf
      - eot
      - otf
      - woff
      - woff2
      # Graphics
      - png
      - jpg
      - jpeg
      - gif
      - tif
      - tiff
      # SVG
      - ico
      - svg
      - eps
      # Java
      - class
      - jar
      - war
      # Doc
      - doc
      - DOC
      - docx
      - DOCX
      - dot
      - DOT
      - pdf
      - PDF
      - rtf
      - RTF
    text:
      #
      - webapp
      - eslintignore
      - prettierignore
      - prettierrc
      - lock
      #
      - bat
      - cmd
      - ps1
      - coffee
      - css
      - cql
      - df
      - ejs
      - tsx
      - html
      - java
      - js
      - json
      - less
      - properties
      - sass
      - scss
      - sh
      - sql
      - txt
      - ts
      - xml
      - yaml
      - yml
      # Documents
      - markdown
      - md
      - adoc
      - textile
      - mustache
      - csv
      - tab
      - tsv
      - txt
      - AUTHORS
      - CHANGELOG
      - CHANGES
      - CONTRIBUTING
      - COPYING
      - copyright
      - COPYRIGHT
      - INSTALL
      - license
      - LICENSE
      - NEWS
      - readme
      - README
      - TODO
      # LINTERS
      - csslintrc
      - eslintrc
      - jscsrc
      - jshintrc
      - jshintignore
      - stylelintrc
      # CONFIGS
      - conf
      - config
      - editorconfig
      - gitattributes
      - gitconfig
      - gitignore
      - htaccess
      - npmignore
      # HEROKU
      - Procfile
      - slugignore
