declare const YAML: any;
declare const modules: any;
declare const _entity: any;
declare const _entities: any;
declare const _allEnum: any;
declare const _: any;
declare const enumObject: any;

declare const baseName: string;
declare const author: string;
declare const serverPort: string;
declare const prefix: string;
declare const suffix: string;
declare const entityPrefix: string;
declare const entitySuffix: string;
declare const dtoSuffix: string;
declare const nativeLanguage: string;
declare const packageFolder: string;
declare const serviceDiscoveryType: string;
declare const websocket: string;
declare const searchEngine: string;
declare const messageBroker: string;
declare const clientPackageManager: string;
declare const buildTool: string;
declare const clientTheme: string;

declare const entityType: "mongoose" | 'typeorm';
declare const database: "mysql" | "mariadb" | "postgres" | "mongodb";
declare const devDatabase: "sqlite" | "mongodb-memory";
declare const prodDatabase: "mysql" | "mariadb" | "postgres" | "mongodb";
